import type { NextPage } from "next";
import Head from "next/head";

const DesignSystem: NextPage = () => {
  return (
    <div className="container">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>Design System page</main>
    </div>
  );
};

export default DesignSystem;
