import type { NextPage } from "next";
import Head from "next/head";

const DesignSystem: NextPage = () => {
  return (
    <div className="bg-dark text-white">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container">
        <h1>Design System</h1>
        <section id="colors" className="flex" style={{ flexDirection: "column" }}>
          <h2>
            <span>01</span> colors
          </h2>
          <div className="flex">
            <div style={{ flex: "1" }}>
              <div
                className="bg-dark text-white"
                style={{ paddingInline: "1rem", paddingBlock: "3rem 1rem", border: "1px solid white" }}
              >
                #0B0D17
              </div>
              <p>
                <span className="text-accent">RGB</span> 11, 13, 23
              </p>
              <p>
                <span className="text-accent">HSL</span> 230°, 35%, 7%
              </p>
            </div>
            <div style={{ flex: "1" }}>
              <div
                className="bg-accent text-dark"
                style={{ paddingInline: "1rem", paddingBlock: "3rem 1rem", border: "1px solid white" }}
              >
                #D0D6F9
              </div>
              <p>
                <span className="text-accent">RGB</span> 208, 214, 249
              </p>
              <p>
                <span className="text-accent">HSL</span> 231°, 77%, 90%
              </p>
            </div>
            <div style={{ flex: "1" }}>
              <div
                className="bg-white text-dark"
                style={{ paddingInline: "1rem", paddingBlock: "3rem 1rem", border: "1px solid white" }}
              >
                #FFFFFF
              </div>
              <p>
                <span className="text-accent">RGB</span> 255, 255, 255
              </p>
              <p>
                <span className="text-accent">HSL</span> 0°, 0%, 100%
              </p>
            </div>
          </div>
        </section>
      </div>
    </div>
  );
};

export default DesignSystem;
