import type { NextPage } from "next";
import Head from "next/head";
import Container from "@/components/Container";
// import Image from "next/image";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <h1>HomePage</h1>
      </Container>
    </>
  );
};

export default Home;
